### ISSUE TITLE
FHIR UC2: Building FHIR clients to pull from FHIR servers

### ISSUE THREAD

**Issue by cottonva** [NIH-NCPI/NCPI_use_case_tracker#17]
**Platforms involved**: Seven Bridges (CAVATICA for Kids First, but can also be used by BDC or the CRDC); however, this work will inform all platform/workspace environments (e.g., Terra) or other FHIR clients (portals). 
**Scientific Lead**: TBD
**Platform Lead**: Michele Mattioni 
**One pager description**: (what research question to be answered, plan of data use and analysis) - in development (is there existing documentation we can point to?)
**Use Case**:  Enable users to pull Kids First clinical, phenotypic data from FHIR server and analyze in cloud-based workspaces. 
**Funding resources**: ODSS supplement to Kids First DRC, CFDE short-term pilot (KF-DRC OT)

**Comment by linikujp** [comment]
@cottonva is this already completed by FHIR WG?

**Comment by cottonva** [comment]
@linikujp - Michele is the lead (I am trying to tag him). I believe this is an ongoing use case. @allisonheath @liberaliscomputing may have updates

**Comment by jackDiGi** [comment]
@mattions ^

**Comment by mattions** [comment]
Hello everyone, as after several discussion, and with the maturation of the use-cases in the NCPI cases, we think it would be a good idea to close this one.

While the work will carry on, the primary use-case we had in mind was a _platform to platform integration_, which does not involve user-researchers (this is deep in the infrastructure, and it's an update towards the new way to do things which updates what is the current integration built back in the days).

I'm closing it now, feel free to reach out in case there are questions.
