### ISSUE TITLE
UC 1.a Create training materials

### ISSUE THREAD

**Issue by NoopDog** [NIH-NCPI/NCPI_use_case_tracker#5]

**Comment by jackDiGi** [comment]
is this related to a specific use case or presentation at the NCPI bi-annual meetings? Or more globally for NCPI Outreach?

Asking because I'm supposed to create some videos but I don't know where :)

**Comment by linikujp** [comment]
This refers to Ia. Since 1a is inactive, this ticket is closed.

**Comment by linikujp** [comment]
This refers to Ia. Since 1a is inactive, this ticket is closed.
